// Code generated by protoc-gen-go.
// source: head/head.proto
// DO NOT EDIT!

/*
Package head is a generated protocol buffer package.

It is generated from these files:
	head/head.proto

It has these top-level messages:
	Vector
	Object
	Frame
	Stream
*/
package head

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Texture int32

const (
	Texture_SHIP          Texture = 0
	Texture_ASTEROID      Texture = 1
	Texture_CONTROL_POINT Texture = 2
	Texture_PROJECTILE    Texture = 3
)

var Texture_name = map[int32]string{
	0: "SHIP",
	1: "ASTEROID",
	2: "CONTROL_POINT",
	3: "PROJECTILE",
}
var Texture_value = map[string]int32{
	"SHIP":          0,
	"ASTEROID":      1,
	"CONTROL_POINT": 2,
	"PROJECTILE":    3,
}

func (x Texture) Enum() *Texture {
	p := new(Texture)
	*p = x
	return p
}
func (x Texture) String() string {
	return proto.EnumName(Texture_name, int32(x))
}
func (x *Texture) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Texture_value, data, "Texture")
	if err != nil {
		return err
	}
	*x = Texture(value)
	return nil
}

type Vector struct {
	X                *float32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y                *float32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	Z                *float32 `protobuf:"fixed32,3,req,name=z" json:"z,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Vector) Reset()         { *m = Vector{} }
func (m *Vector) String() string { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()    {}

func (m *Vector) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Vector) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Vector) GetZ() float32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

type Object struct {
	ID               *int64   `protobuf:"varint,1,req" json:"ID,omitempty"`
	Pos              *Vector  `protobuf:"bytes,2,req,name=pos" json:"pos,omitempty"`
	Radius           *float32 `protobuf:"fixed32,3,req,name=radius" json:"radius,omitempty"`
	Tex              *Texture `protobuf:"varint,4,req,name=tex,enum=head.Texture" json:"tex,omitempty"`
	TexCustom        *string  `protobuf:"bytes,5,opt,name=tex_custom" json:"tex_custom,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}

func (m *Object) GetID() int64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Object) GetPos() *Vector {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *Object) GetRadius() float32 {
	if m != nil && m.Radius != nil {
		return *m.Radius
	}
	return 0
}

func (m *Object) GetTex() Texture {
	if m != nil && m.Tex != nil {
		return *m.Tex
	}
	return Texture_SHIP
}

func (m *Object) GetTexCustom() string {
	if m != nil && m.TexCustom != nil {
		return *m.TexCustom
	}
	return ""
}

type Frame struct {
	Object           []*Object `protobuf:"bytes,1,rep,name=object" json:"object,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Frame) Reset()         { *m = Frame{} }
func (m *Frame) String() string { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()    {}

func (m *Frame) GetObject() []*Object {
	if m != nil {
		return m.Object
	}
	return nil
}

type Stream struct {
	Frame            []*Frame `protobuf:"bytes,2,rep,name=frame" json:"frame,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}

func (m *Stream) GetFrame() []*Frame {
	if m != nil {
		return m.Frame
	}
	return nil
}

func init() {
	proto.RegisterEnum("head.Texture", Texture_name, Texture_value)
}
